# Production / exam profile — PostgreSQL with Flyway migrations and DB triggers
spring.datasource.url=jdbc:postgresql://localhost:5433/utility_billing
spring.datasource.username=postgres
spring.datasource.password=micofaith1234

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
