ALTER TABLE bills ADD COLUMN IF NOT EXISTS meter_id BIGINT REFERENCES meters(id);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS reading_id BIGINT REFERENCES meter_readings(id);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS consumption NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT FALSE;
