services:
  postgres:
    image: postgres:16
    container_name: utility-billing-db
    environment:
      POSTGRES_DB: utility_billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - utility_billing_data:/var/lib/postgresql/data

volumes:
  utility_billing_data:
